// 运行时消息类型总表。
// 项目中的 popup、background、content script 之间通信都应复用这里的常量，
// 而不是在各处直接写裸字符串。
export const MESSAGE_TYPES = {
  GET_CURRENT_PAGE_ANNOTATIONS: 'GET_CURRENT_PAGE_ANNOTATIONS',
  CREATE_ANNOTATION_FROM_SELECTION: 'CREATE_ANNOTATION_FROM_SELECTION',
  TRANSLATE_SELECTION: 'TRANSLATE_SELECTION',
  REMOVE_ANNOTATION_BY_ID: 'REMOVE_ANNOTATION_BY_ID',
  REMOVE_ANNOTATIONS_FROM_SELECTION: 'REMOVE_ANNOTATIONS_FROM_SELECTION',
  CLEAR_CURRENT_PAGE_ANNOTATIONS: 'CLEAR_CURRENT_PAGE_ANNOTATIONS',
  EXPORT_ANNOTATIONS: 'EXPORT_ANNOTATIONS',
  IMPORT_ANNOTATIONS: 'IMPORT_ANNOTATIONS',
  RESTORE_PAGE_ANNOTATIONS: 'RESTORE_PAGE_ANNOTATIONS',
  GET_TRANSLATION_SETTINGS: 'GET_TRANSLATION_SETTINGS',
  SAVE_TRANSLATION_SETTINGS: 'SAVE_TRANSLATION_SETTINGS'
} as const