// 运行时消息类型总表。
// 项目中的 popup、background、content script 之间通信都应复用这里的常量，
// 而不是在各处直接写裸字符串。
export const MESSAGE_TYPES = {
  GET_CURRENT_PAGE_ANNOTATIONS: 'GET_CURRENT_PAGE_ANNOTATIONS',
  CREATE_ANNOTATION_FROM_SELECTION: 'CREATE_ANNOTATION_FROM_SELECTION',
  NAVIGATE_TO_ANNOTATION: 'NAVIGATE_TO_ANNOTATION',
  TRANSLATE_SELECTION: 'TRANSLATE_SELECTION',
  REMOVE_ANNOTATION_BY_ID: 'REMOVE_ANNOTATION_BY_ID',
  REMOVE_ANNOTATIONS_FROM_SELECTION: 'REMOVE_ANNOTATIONS_FROM_SELECTION',
  CLEAR_CURRENT_PAGE_ANNOTATIONS: 'CLEAR_CURRENT_PAGE_ANNOTATIONS',
  EXPORT_ANNOTATIONS: 'EXPORT_ANNOTATIONS',
  IMPORT_ANNOTATIONS: 'IMPORT_ANNOTATIONS',
  RESTORE_PAGE_ANNOTATIONS: 'RESTORE_PAGE_ANNOTATIONS',
  GET_TRANSLATION_PREFERENCES: 'GET_TRANSLATION_PREFERENCES',
  SAVE_TRANSLATION_PREFERENCES: 'SAVE_TRANSLATION_PREFERENCES',
  GET_BACKEND_CONFIG: 'GET_BACKEND_CONFIG',
  REGISTER_BACKEND_ACCOUNT: 'REGISTER_BACKEND_ACCOUNT',
  LOGIN_BACKEND_ACCOUNT: 'LOGIN_BACKEND_ACCOUNT',
  LOGOUT_BACKEND_ACCOUNT: 'LOGOUT_BACKEND_ACCOUNT',
  DELETE_BACKEND_ACCOUNT: 'DELETE_BACKEND_ACCOUNT',
  GET_BACKEND_ACCOUNT: 'GET_BACKEND_ACCOUNT',
  GET_ACCOUNT_VERIFICATION_STATUS: 'GET_ACCOUNT_VERIFICATION_STATUS',
  SEND_VERIFICATION_EMAIL: 'SEND_VERIFICATION_EMAIL',
  VERIFY_EMAIL_TOKEN: 'VERIFY_EMAIL_TOKEN',
  PULL_CLOUD_STATE: 'PULL_CLOUD_STATE',
  PREVIEW_CLOUD_UPLOAD: 'PREVIEW_CLOUD_UPLOAD',
  CONFIRM_CLOUD_UPLOAD: 'CONFIRM_CLOUD_UPLOAD',
  SYNC_WITH_CLOUD: 'SYNC_WITH_CLOUD',
  SAVE_BACKEND_CONFIG: 'SAVE_BACKEND_CONFIG',
  GET_TRANSLATION_PROVIDER_STATUS: 'GET_TRANSLATION_PROVIDER_STATUS',
  SAVE_TRANSLATION_PROVIDER_CONFIG: 'SAVE_TRANSLATION_PROVIDER_CONFIG',
  DELETE_TRANSLATION_PROVIDER_CONFIG: 'DELETE_TRANSLATION_PROVIDER_CONFIG'
} as const